---
- name: restart wireguard
  ansible.builtin.service:
    name: wireguard
    state: restarted
  become: true

- name: reload wireguard
  ansible.builtin.command:
    cmd: "/usr/sbin/service wireguard reload"
  changed_when: true
  become: true
