---
galaxy_info:
  role_name: monitoring
  namespace: wesmarcum
  author: Wes Marcum
  description: This role installs and configures common monitoring tools.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - freebsd
