---
# Tasks for system monitoring.
- name: Enable monitoring
  ansible.builtin.import_tasks: "tasks/monitoring.yml"
  when: firewall_monitoring_enable | bool
  tags:
    - monitoring

# Disable system monitoring.
- name: Disable monitoring
  ansible.builtin.include_tasks:
    file: "tasks/monitoring_disable.yml"
    apply:
      tags:
        - monitoring
  when: firewall_monitoring_enable | bool is false
  tags:
    - monitoring
