---
- name: Uninstall monitoring packages
  ansible.builtin.package:
    name: "{{ firewall_monitoring_packages }}"
    state: absent
  become: true

- name: Remove vnstat
  when: firewall_monitoring_vnstat_enable | bool is false
  block:
    - name: Stop vnstat
      ansible.builtin.service:
        name: vnstat
        state: stopped
      become: true

    - name: Remove vnstat logfile
      ansible.builtin.file:
        path: "{{ firewall_monitoring_vnstat_logfile }}"
        state: absent
      become: true
      when: firewall_monitoring_vnstat_uselogging | int == 1

    - name: Remove vnstat db dir
      ansible.builtin.file:
        path: "{{ firewall_monitoring_vnstat_db_path }}"
        state: absent
      become: true

    - name: Remove vnstat service file
      ansible.builtin.file:
        path: "/etc/rc.conf.d/vnstat"
        state: absent
      become: true

    - name: Remove vnstat configuration
      ansible.builtin.file:
        path: "{{ firewall_monitoring_vnstat_config }}"
        state: absent
      become: true

    - name: Remove newsyslog file for vnstat
      ansible.builtin.file:
        path: "/usr/local/etc/newsyslog.conf.d/vnstat.conf"
        state: absent
      become: true
      when: firewall_monitoring_vnstat_uselogging | int == 1

- name: Disable email reports
  when: firewall_monitoring_email_enable | bool is false
  block:
    - name: Restore dma configuration
      ansible.builtin.copy:
        src: "etc/dma/dma.conf"
        dest: "/etc/dma/dma.conf"
        owner: root
        group: wheel
        mode: '0644'
      become: true

    - name: Template mail aliases
      ansible.builtin.template:
        src: "etc/aliases.j2"
        dest: "/etc/mail/aliases"
        owner: root
        group: wheel
        mode: '0644'
      become: true

    - name: Set mailer configuration to default
      ansible.builtin.copy:
        src: "etc/mail/mailer.conf"
        dest: "/etc/mail/mailer.conf"
        owner: root
        group: wheel
        mode: 0644
      become: true

    - name: Remove periodic configuration
      ansible.builtin.file:
        path: "/etc/periodic.conf"
        state: absent
      become: true

    - name: Template mail aliases
      ansible.builtin.template:
        src: "etc/aliases.j2"
        dest: "/etc/mail/aliases"
        owner: root
        group: wheel
        mode: '0644'
      become: true
