---
### Wireguard

firewall_wireguard_enable: true
firewall_wireguard_path: "/usr/local/etc/wireguard"

# Use kernel module, otherwise use go.
firewall_wireguard_use_kmod: true

# Environment variables to pass - only applies to the go implementation.
firewall_wireguard_env: ""

# List of wireguard interfaces and parameters to configure.
firewall_wireguard_conf: []
