---
# Install cpu-microcode for microcode updates
- name: Install cpu-microcode for microcode updates
  ansible.builtin.package:
    name: cpu-microcode
    state: present
  become: true

- name: Start the microcode update service
  ansible.builtin.service:
    name: microcode_update
    state: started
  become: true
  changed_when: false
